version: '3.8'

services:
  php:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: hinto_php
    restart: unless-stopped
    volumes:
      - ./api:/var/www/html
    depends_on:
      - nginx
      - db
    networks:
      - symfony

  nginx:
    image: nginx:alpine
    container_name: hinto_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./api:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - symfony

  db:
    image: postgres
    container_name: hinto_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - symfony

volumes:
  pgdata:

networks:
  symfony:
